# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
benchmarks:
  AtCoderDevHs-benchmarks:
    dependencies:
    - base
    - AtCoderDevHs
    - criterion
    - array
    - base
    - bytestring
    - containers
    - deepseq
    - directory
#    - haskell2010
#    - haskell98
    - hpc
#    - old-locale
#    - old-time
    - pretty
    - process
    - template-haskell
    - time
    - transformers
#    - unix
#    - Win32
    - xhtml
    - async
    - attoparsec
    - case-insensitive
    - cgi
    - exceptions
#    - fgl
#    - GLURaw
#    - GLUT
    - half
    - hashable
#    - haskell-src
    - html
#    - HTTP
    - HUnit
    - mtl
    - multipart
#    - network
#    - network-uri
#    - ObjectName
#    - OpenGL
#    - OpenGLRaw
    - parallel
    - parsec
    - primitive
    - QuickCheck
    - random
    - regex-base
    - regex-compat
    - regex-posix
#    - scientific
    - split
    - StateVar
    - stm
    - syb
    - text
    - tf-random
    - transformers
    - transformers-compat
    - unordered-containers
    - vector
#    - xhtml
#    - zlib
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: benchmark
category: Other
description: AtCoderDevHs is a new Haskeleton package.
executables:
  AtCoderDevHs:
    dependencies:
# for test and benchmark ###
    -  tasty
    -  tasty-hspec
    - criterion
#### end  ####
    - AtCoderDevHs
    - array
    - base
    - bytestring
    - containers
    - deepseq
    - directory
#    - haskell2010
#    - haskell98
    - hpc
#    - old-locale
#    - old-time
    - pretty
    - process
    - template-haskell
    - time
    - transformers
#    - unix
#    - Win32
    - async
    - attoparsec
    - case-insensitive
    - exceptions
#    - GLURaw
#    - GLUT
    - half
    - hashable
    - html
#    - HTTP
    - HUnit
    - mtl
    - multipart
#    - network
#    - network-uri
#    - ObjectName
#    - OpenGL
#    - OpenGLRaw
    - parallel
    - parsec
    - primitive
    - QuickCheck
    - random
    - regex-base
    - regex-compat
    - regex-posix
    - split
    - StateVar
    - stm
    - syb
    - text
    - tf-random
    - transformers
    - transformers-compat
    - unordered-containers
    - vector
#    - xhtml
    ghc-options:
    -  -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: executable
extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
- stack.yaml
ghc-options: -Wall
github: no-moree-ria10/AtCoderDevHs
library:
  dependencies:
    - array
# for test and benchmark ###
    -  tasty
    -  tasty-hspec
    - criterion
#### end  ####
    - tasty-hspec
    - base
    - bytestring
    - containers
    - deepseq
    - directory
#    - haskell2010
#    - haskell98
    - hpc
#    - old-locale
#    - old-time
    - pretty
    - process
    - template-haskell
    - time
    - transformers
#    - unix
#    - Win32
    - async
    - attoparsec
    - case-insensitive
    - cgi
    - exceptions
#    - GLURaw
#    - GLUT
    - half
    - hashable
#    - HTTP
    - HUnit
    - mtl
    - multipart
#    - network
#    - network-uri
#    - ObjectName
#    - OpenGL
#    - OpenGLRaw
    - parallel
    - parsec
    - primitive
    - QuickCheck
    - random
    - regex-base
    - regex-compat
    - regex-posix
    - scientific
    - split
    - StateVar
    - stm
    - syb
    - text
    - tf-random
    - transformers
    - transformers-compat
    - unordered-containers
    - vector
#    - xhtml
  source-dirs: library
license: MIT
maintainer: OtaTakuma
name: AtCoderDevHs
synopsis: A new Haskeleton package.
tests:
  AtCoderDevHs-test-suite:
    dependencies:
    -  base
    -  AtCoderDevHs
    -  tasty
    -  tasty-hspec
    - array
    - bytestring
    - containers
    - deepseq
    - directory
#    - haskell2010
#    - haskell98
    - hpc
#    - old-locale
#    - old-time
    - pretty
    - process
    - template-haskell
    - time
    - transformers
#    - unix
#    - Win32
    - async
    - attoparsec
    - case-insensitive
    - exceptions
#    - GLURaw
#    - GLUT
    - half
    - hashable
#    - HTTP
    - HUnit
    - mtl
    - multipart
#    - network
#    - network-uri
#    - ObjectName
#    - OpenGL
#    - OpenGLRaw
    - parallel
    - parsec
    - primitive
    - QuickCheck
    - random
    - regex-base
    - regex-compat
    - regex-posix
    - scientific
    - split
    - StateVar
    - stm
    - syb
    - text
    - tf-random
    - transformers
    - transformers-compat
    - unordered-containers
    - vector
#    - xhtml
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: test-suite
version: '0.0.0'
