# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
benchmarks:
  AtCoderDevHs-benchmarks:
    dependencies:
    - base
    - AtCoderDevHs
    - criterion
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: benchmark
category: Other
description: AtCoderDevHs is a new Haskeleton package.
executables:
  AtCoderDevHs:
    dependencies:
    - base
    - AtCoderDevHs
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: executable
extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
- stack.yaml
ghc-options: -Wall
github: no-moree-ria10/AtCoderDevHs
library:
  dependencies:
  - base
  - tasty
  - tasty-hspec
  - array
  - bytestring
  - containers
  - deepseq
  - async
  - attoparsec
  - mtl
  - regex-base
  - regex-compat
  - regex-posix
  - stm
  - text
  - unordered-containers
  - vector
  - primitive
  source-dirs: library
license: MIT
maintainer: OtaTakuma
name: AtCoderDevHs
synopsis: A new Haskeleton package.
tests:
  AtCoderDevHs-test-suite:
    dependencies:
    - base
    - AtCoderDevHs
    - tasty
    - tasty-hspec
    - vector
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: test-suite
version: '0.0.0'
